#import = ["/home/usman/.config/alacritty/themes/themes/everforest_dark.toml"] 
import = ["/home/stark/.config/alacritty/everforest-colors.toml", "/home/stark/.config/alacritty/fonts.toml"]
#import = ["/home/stark/.config/alacritty/fonts.toml"]
live_config_reload = true

[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[shell]
program = "/usr/bin/fish"

[window]
decorations = "full"
dynamic_title = true
#history = 10000
#multiplier = 3
opacity = 0.95
startup_mode = "Windowed"

[window.dimensions]
columns = 130
lines = 35

[window.padding]
x = 10
y = 10

# Colors (Everforest Dark)

# Default colors

